

/******************************************************************************
 Copyright (C) 2012      Advanced Digital Chips Inc. 
						http://www.adc.co.kr
 Author : Software Team.

 SURFACE Image can be generated by "pc-util/MakeSurface2.exe"

******************************************************************************/
#include "adstar.h"
#include "surface.h"

// version 0x100
typedef struct {
	unsigned int magic;
	unsigned int version;
	unsigned short w;//image width
	unsigned short h;//image height
	unsigned short lpitch ;// allocated memory width 8,16,32,64,128,256,512,1024
	unsigned char bCompress;//0 : no compress, 1 : RLE
	unsigned char bpp;
}SURF_HEADER; 

SURFACE* loadsurf(char* fname)
{
	SURFACE* surf;
	SURF_HEADER surfheader ;
	
	FIL fp;
	int nRead;
	FRESULT res = f_open(&fp,fname,FA_READ|FA_OPEN_EXISTING);
	if( res != FR_OK )
	{
		DEBUGPRINTF("Cannot open : %s\r\n", fname);
		return 0;
	}
	int fsize = f_size(&fp);
	if(fsize<sizeof(SURF_HEADER))
		return 0;

	f_read(&fp,&surfheader,sizeof(SURF_HEADER),&nRead);
	if(surfheader.magic != ( ('S') + ('U'<<8) + ('R'<<16) + ('F'<<24) ))
	{
		debugstring("Invalid SUF-ID\r\n");
		f_close(&fp);
		return 0;
	}
	surf = create_surface(surfheader.w,surfheader.h,surfheader.bpp);
	if(surf->pitch < surfheader.lpitch)
	{
		debugstring("Invalid line pictch\r\n");
		f_close(&fp);
		release_surface(surf);
		return 0;
	}
	surf->pitch = surfheader.lpitch;
	
	f_read(&fp,surf->pixels,fsize-sizeof(SURF_HEADER),&nRead);
	f_close(&fp);
	return surf;
}
