#====================================================================
# File automatically generated by ES3  
# This file regenerated each time you run EISC Studio, so save under a 
# new name if you hand edit, or it will be overwritten.
#				www.adc.co.kr
#====================================================================



CC	=	ae32000-elf-gcc
AS	=	ae32000-elf-as
LD	=	ae32000-elf-ld
AR	=	ae32000-elf-ar
OBJCOPY	=	ae32000-elf-objcopy
OBJDUMP	=	ae32000-elf-objdump
CFLAGS	=	 -O2  -g -Wall -Wall 
ASFLAGS	=	 -gstabs 
LDFLAGS	=	-Wall -nostartfiles -lgcc -lc -lm
DISFLAGS	=	-dShxl
#====== Directory =====
OUTPUTDIR	=	../lib/
OBJDIR	=	obj/
INCDIR	=	\
	 -I"../include"\
	 -I"../include/egl"
LIBDIR	=	
LIBS	=	

SOURCES	 += cache_util.S
SOURCES	 += crtc.c
SOURCES	 += dma.c
SOURCES	 += error.c
SOURCES	 += interrupt.c
SOURCES	 += mp3play.c
SOURCES	 += nandctrl.c
SOURCES	 += pmu.c
SOURCES	 += sdcard.c
SOURCES	 += serialflash.c
SOURCES	 += soundmixer.c
SOURCES	 += spi.c
SOURCES	 += timer.c
SOURCES	 += twi.c
SOURCES	 += uart.c
SOURCES	 += usb.c
SOURCES	 += util.c
SOURCES	 += egl/egl_base.c
SOURCES	 += egl/egl_private.c
SOURCES	 += egl/egl_window.c
SOURCES	 += egl/theme/default_theme.c
SOURCES	 += egl/primitives/colors.c
SOURCES	 += egl/primitives/draw_arc.c
SOURCES	 += egl/primitives/draw_line.c
SOURCES	 += egl/primitives/draw_poly.c
SOURCES	 += egl/primitives/draw_rect.c
SOURCES	 += egl/primitives/draw_thickline.c
SOURCES	 += egl/image/loadbmp.c
SOURCES	 += egl/image/loadjpg.c
SOURCES	 += egl/image/loadpng.c
SOURCES	 += egl/image/loadsurf.c
SOURCES	 += egl/image/loadtga.c
SOURCES	 += egl/font/textout.c
SOURCES	 += fatfs/diskio.c
SOURCES	 += fatfs/ff.c
SOURCES	 += egl/object/egl_button.c
SOURCES	 += egl/object/egl_checkbutton.c
SOURCES	 += egl/object/egl_custom_object.c
SOURCES	 += egl/object/egl_label.c
SOURCES	 += egl/object/egl_listbox.c
SOURCES	 += egl/object/egl_messagebox.c
SOURCES	 += egl/object/egl_picture.c
SOURCES	 += egl/object/egl_progressbar.c
SOURCES	 += egl/object/egl_scrollbar.c
SOURCES	 += egl/object/egl_slider.c
SOURCES	 += egl/object/egl_toggle_image.c
SOURCES	 += egl/object/egl_bar_gauge.c
SOURCES	 += egl/object/egl_circle_gauge.c
SOURCES	 += egl/object/egl_image_button.c
SOURCES	 += egl/primitives/draw_line_aa.c
SOURCES	 += egl/primitives/draw_polyfill.c
SOURCES	 += egl/font/bitmapfont.c
SOURCES	 += egl/font/egl_font.c
SOURCES	 += fatfs/readfile.c
SOURCES	 += egl/object/egl_animation.c
SOURCES	 += egl/font/unicode_codec.c
SOURCES	 += egl/util/fixed_sincos.c
SOURCES	 += egl/primitives/draw_legacy.c
SOURCES	 += egl/primitives/draw_roundrect.c
SOURCES	 += egl/surface/surface.c
SOURCES	 += egl/surface/surface_createfrom.c
SOURCES	 += egl/surface/drawsurfacescale.c
SOURCES	 += egl/font/bitfont.c
SOURCES	 += egl/font/textout_inbox.c

OBJECTS	 += ${OBJDIR}cache_util.o
OBJECTS	 += ${OBJDIR}crtc.o
OBJECTS	 += ${OBJDIR}dma.o
OBJECTS	 += ${OBJDIR}error.o
OBJECTS	 += ${OBJDIR}interrupt.o
OBJECTS	 += ${OBJDIR}mp3play.o
OBJECTS	 += ${OBJDIR}nandctrl.o
OBJECTS	 += ${OBJDIR}pmu.o
OBJECTS	 += ${OBJDIR}sdcard.o
OBJECTS	 += ${OBJDIR}serialflash.o
OBJECTS	 += ${OBJDIR}soundmixer.o
OBJECTS	 += ${OBJDIR}spi.o
OBJECTS	 += ${OBJDIR}timer.o
OBJECTS	 += ${OBJDIR}twi.o
OBJECTS	 += ${OBJDIR}uart.o
OBJECTS	 += ${OBJDIR}usb.o
OBJECTS	 += ${OBJDIR}util.o
OBJECTS	 += ${OBJDIR}egl_base.o
OBJECTS	 += ${OBJDIR}egl_private.o
OBJECTS	 += ${OBJDIR}egl_window.o
OBJECTS	 += ${OBJDIR}default_theme.o
OBJECTS	 += ${OBJDIR}colors.o
OBJECTS	 += ${OBJDIR}draw_arc.o
OBJECTS	 += ${OBJDIR}draw_line.o
OBJECTS	 += ${OBJDIR}draw_poly.o
OBJECTS	 += ${OBJDIR}draw_rect.o
OBJECTS	 += ${OBJDIR}draw_thickline.o
OBJECTS	 += ${OBJDIR}loadbmp.o
OBJECTS	 += ${OBJDIR}loadjpg.o
OBJECTS	 += ${OBJDIR}loadpng.o
OBJECTS	 += ${OBJDIR}loadsurf.o
OBJECTS	 += ${OBJDIR}loadtga.o
OBJECTS	 += ${OBJDIR}textout.o
OBJECTS	 += ${OBJDIR}diskio.o
OBJECTS	 += ${OBJDIR}ff.o
OBJECTS	 += ${OBJDIR}egl_button.o
OBJECTS	 += ${OBJDIR}egl_checkbutton.o
OBJECTS	 += ${OBJDIR}egl_custom_object.o
OBJECTS	 += ${OBJDIR}egl_label.o
OBJECTS	 += ${OBJDIR}egl_listbox.o
OBJECTS	 += ${OBJDIR}egl_messagebox.o
OBJECTS	 += ${OBJDIR}egl_picture.o
OBJECTS	 += ${OBJDIR}egl_progressbar.o
OBJECTS	 += ${OBJDIR}egl_scrollbar.o
OBJECTS	 += ${OBJDIR}egl_slider.o
OBJECTS	 += ${OBJDIR}egl_toggle_image.o
OBJECTS	 += ${OBJDIR}egl_bar_gauge.o
OBJECTS	 += ${OBJDIR}egl_circle_gauge.o
OBJECTS	 += ${OBJDIR}egl_image_button.o
OBJECTS	 += ${OBJDIR}draw_line_aa.o
OBJECTS	 += ${OBJDIR}draw_polyfill.o
OBJECTS	 += ${OBJDIR}bitmapfont.o
OBJECTS	 += ${OBJDIR}egl_font.o
OBJECTS	 += ${OBJDIR}readfile.o
OBJECTS	 += ${OBJDIR}egl_animation.o
OBJECTS	 += ${OBJDIR}unicode_codec.o
OBJECTS	 += ${OBJDIR}fixed_sincos.o
OBJECTS	 += ${OBJDIR}draw_legacy.o
OBJECTS	 += ${OBJDIR}draw_roundrect.o
OBJECTS	 += ${OBJDIR}surface.o
OBJECTS	 += ${OBJDIR}surface_createfrom.o
OBJECTS	 += ${OBJDIR}drawsurfacescale.o
OBJECTS	 += ${OBJDIR}bitfont.o
OBJECTS	 += ${OBJDIR}textout_inbox.o

DEPS	 += ${OBJDIR}cache_util.d
DEPS	 += ${OBJDIR}crtc.d
DEPS	 += ${OBJDIR}dma.d
DEPS	 += ${OBJDIR}error.d
DEPS	 += ${OBJDIR}interrupt.d
DEPS	 += ${OBJDIR}mp3play.d
DEPS	 += ${OBJDIR}nandctrl.d
DEPS	 += ${OBJDIR}pmu.d
DEPS	 += ${OBJDIR}sdcard.d
DEPS	 += ${OBJDIR}serialflash.d
DEPS	 += ${OBJDIR}soundmixer.d
DEPS	 += ${OBJDIR}spi.d
DEPS	 += ${OBJDIR}timer.d
DEPS	 += ${OBJDIR}twi.d
DEPS	 += ${OBJDIR}uart.d
DEPS	 += ${OBJDIR}usb.d
DEPS	 += ${OBJDIR}util.d
DEPS	 += ${OBJDIR}egl_base.d
DEPS	 += ${OBJDIR}egl_private.d
DEPS	 += ${OBJDIR}egl_window.d
DEPS	 += ${OBJDIR}default_theme.d
DEPS	 += ${OBJDIR}colors.d
DEPS	 += ${OBJDIR}draw_arc.d
DEPS	 += ${OBJDIR}draw_line.d
DEPS	 += ${OBJDIR}draw_poly.d
DEPS	 += ${OBJDIR}draw_rect.d
DEPS	 += ${OBJDIR}draw_thickline.d
DEPS	 += ${OBJDIR}loadbmp.d
DEPS	 += ${OBJDIR}loadjpg.d
DEPS	 += ${OBJDIR}loadpng.d
DEPS	 += ${OBJDIR}loadsurf.d
DEPS	 += ${OBJDIR}loadtga.d
DEPS	 += ${OBJDIR}textout.d
DEPS	 += ${OBJDIR}diskio.d
DEPS	 += ${OBJDIR}ff.d
DEPS	 += ${OBJDIR}egl_button.d
DEPS	 += ${OBJDIR}egl_checkbutton.d
DEPS	 += ${OBJDIR}egl_custom_object.d
DEPS	 += ${OBJDIR}egl_label.d
DEPS	 += ${OBJDIR}egl_listbox.d
DEPS	 += ${OBJDIR}egl_messagebox.d
DEPS	 += ${OBJDIR}egl_picture.d
DEPS	 += ${OBJDIR}egl_progressbar.d
DEPS	 += ${OBJDIR}egl_scrollbar.d
DEPS	 += ${OBJDIR}egl_slider.d
DEPS	 += ${OBJDIR}egl_toggle_image.d
DEPS	 += ${OBJDIR}egl_bar_gauge.d
DEPS	 += ${OBJDIR}egl_circle_gauge.d
DEPS	 += ${OBJDIR}egl_image_button.d
DEPS	 += ${OBJDIR}draw_line_aa.d
DEPS	 += ${OBJDIR}draw_polyfill.d
DEPS	 += ${OBJDIR}bitmapfont.d
DEPS	 += ${OBJDIR}egl_font.d
DEPS	 += ${OBJDIR}readfile.d
DEPS	 += ${OBJDIR}egl_animation.d
DEPS	 += ${OBJDIR}unicode_codec.d
DEPS	 += ${OBJDIR}fixed_sincos.d
DEPS	 += ${OBJDIR}draw_legacy.d
DEPS	 += ${OBJDIR}draw_roundrect.d
DEPS	 += ${OBJDIR}surface.d
DEPS	 += ${OBJDIR}surface_createfrom.d
DEPS	 += ${OBJDIR}drawsurfacescale.d
DEPS	 += ${OBJDIR}bitfont.d
DEPS	 += ${OBJDIR}textout_inbox.d



#====== TAGET Define =====
TARGET	=	$(OUTPUTDIR)libadStar.a

BINARY	=	$(TARGET).bin

HEX	=	$(TARGET).hex

DISASSEMBLE	=	$(TARGET).dis

ALL	:	$(TARGET) 

all	:	$(TARGET)

binary	:	$(BINARY)

bin	:	$(BINARY)

hex	:	$(HEX)

disassemble	:	$(DISASSEMBLE)

dis	:	$(DISASSEMBLE)

clean	:
	@echo.exe 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@echo.exe ' '

cleanall	:
	@echo.exe 'Deleting intermediate and output files... '
	rm -f $(OBJECTS) $(TARGET) $(DISASSEMBLE) $(BINARY) $(DEPS)
	@echo.exe ' '

cleanobj	:
	@echo.exe 'Deleting intermediate files... '
	rm -f $(OBJECTS) 
	@echo.exe ' '

cleanbin	:
	rm -f $(BINARY)
	@echo.exe ' '

cleandis	:
	rm -f $(DISASSEMBLE)
	@echo.exe ' '

ifeq ($(FULLMSG),no)
ECHOMARK = @
else
ECHOMARK = 
endif

-include ${OBJDIR}cache_util.d
-include ${OBJDIR}crtc.d
-include ${OBJDIR}dma.d
-include ${OBJDIR}error.d
-include ${OBJDIR}interrupt.d
-include ${OBJDIR}mp3play.d
-include ${OBJDIR}nandctrl.d
-include ${OBJDIR}pmu.d
-include ${OBJDIR}sdcard.d
-include ${OBJDIR}serialflash.d
-include ${OBJDIR}soundmixer.d
-include ${OBJDIR}spi.d
-include ${OBJDIR}timer.d
-include ${OBJDIR}twi.d
-include ${OBJDIR}uart.d
-include ${OBJDIR}usb.d
-include ${OBJDIR}util.d
-include ${OBJDIR}egl_base.d
-include ${OBJDIR}egl_private.d
-include ${OBJDIR}egl_window.d
-include ${OBJDIR}default_theme.d
-include ${OBJDIR}colors.d
-include ${OBJDIR}draw_arc.d
-include ${OBJDIR}draw_line.d
-include ${OBJDIR}draw_poly.d
-include ${OBJDIR}draw_rect.d
-include ${OBJDIR}draw_thickline.d
-include ${OBJDIR}loadbmp.d
-include ${OBJDIR}loadjpg.d
-include ${OBJDIR}loadpng.d
-include ${OBJDIR}loadsurf.d
-include ${OBJDIR}loadtga.d
-include ${OBJDIR}textout.d
-include ${OBJDIR}diskio.d
-include ${OBJDIR}ff.d
-include ${OBJDIR}egl_button.d
-include ${OBJDIR}egl_checkbutton.d
-include ${OBJDIR}egl_custom_object.d
-include ${OBJDIR}egl_label.d
-include ${OBJDIR}egl_listbox.d
-include ${OBJDIR}egl_messagebox.d
-include ${OBJDIR}egl_picture.d
-include ${OBJDIR}egl_progressbar.d
-include ${OBJDIR}egl_scrollbar.d
-include ${OBJDIR}egl_slider.d
-include ${OBJDIR}egl_toggle_image.d
-include ${OBJDIR}egl_bar_gauge.d
-include ${OBJDIR}egl_circle_gauge.d
-include ${OBJDIR}egl_image_button.d
-include ${OBJDIR}draw_line_aa.d
-include ${OBJDIR}draw_polyfill.d
-include ${OBJDIR}bitmapfont.d
-include ${OBJDIR}egl_font.d
-include ${OBJDIR}readfile.d
-include ${OBJDIR}egl_animation.d
-include ${OBJDIR}unicode_codec.d
-include ${OBJDIR}fixed_sincos.d
-include ${OBJDIR}draw_legacy.d
-include ${OBJDIR}draw_roundrect.d
-include ${OBJDIR}surface.d
-include ${OBJDIR}surface_createfrom.d
-include ${OBJDIR}drawsurfacescale.d
-include ${OBJDIR}bitfont.d
-include ${OBJDIR}textout_inbox.d

#============= TARGET ====================
${TARGET} : Makefile.mk ${OBJECTS} ${LIBS}
	@echo.exe 'Linking...'
	$(ECHOMARK)$(AR) $(ARFLAGS) $(TARGET) $(OBJECTS) $(LIBS)
	@echo.exe 'Finished building : $@ '
	@echo.exe ' '

$(BINARY): $(TARGET)
	@echo.exe 'Generating binary file...'
	$(ECHOMARK)$(OBJCOPY) -O binary $(TARGET) $@
	@echo.exe 'Finished building : $@ '
	@echo.exe ' '
	@echo.exe 'Program section information '
	$(ECHOMARK)size $(TARGET)
	@echo.exe ' '
$(DISASSEMBLE) : $(TARGET)
	@echo.exe 'Generating disassemble file...'
	$(ECHOMARK)$(OBJDUMP) $(DISFLAGS) $(TARGET) > $@ 
	@echo.exe 'Finished building : $@ '
	@echo.exe ' '
${OBJDIR}cache_util.o : cache_util.S
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) -Wa,$(ASFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}crtc.o : crtc.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}dma.o : dma.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}error.o : error.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}interrupt.o : interrupt.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}mp3play.o : mp3play.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}nandctrl.o : nandctrl.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}pmu.o : pmu.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}sdcard.o : sdcard.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}serialflash.o : serialflash.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}soundmixer.o : soundmixer.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}spi.o : spi.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}timer.o : timer.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}twi.o : twi.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}uart.o : uart.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}usb.o : usb.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}util.o : util.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_base.o : egl/egl_base.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_private.o : egl/egl_private.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_window.o : egl/egl_window.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}default_theme.o : egl/theme/default_theme.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}colors.o : egl/primitives/colors.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}draw_arc.o : egl/primitives/draw_arc.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}draw_line.o : egl/primitives/draw_line.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}draw_poly.o : egl/primitives/draw_poly.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}draw_rect.o : egl/primitives/draw_rect.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}draw_thickline.o : egl/primitives/draw_thickline.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}loadbmp.o : egl/image/loadbmp.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}loadjpg.o : egl/image/loadjpg.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}loadpng.o : egl/image/loadpng.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}loadsurf.o : egl/image/loadsurf.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}loadtga.o : egl/image/loadtga.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}textout.o : egl/font/textout.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}diskio.o : fatfs/diskio.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}ff.o : fatfs/ff.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_button.o : egl/object/egl_button.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_checkbutton.o : egl/object/egl_checkbutton.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_custom_object.o : egl/object/egl_custom_object.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_label.o : egl/object/egl_label.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_listbox.o : egl/object/egl_listbox.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_messagebox.o : egl/object/egl_messagebox.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_picture.o : egl/object/egl_picture.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_progressbar.o : egl/object/egl_progressbar.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_scrollbar.o : egl/object/egl_scrollbar.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_slider.o : egl/object/egl_slider.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_toggle_image.o : egl/object/egl_toggle_image.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_bar_gauge.o : egl/object/egl_bar_gauge.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_circle_gauge.o : egl/object/egl_circle_gauge.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_image_button.o : egl/object/egl_image_button.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}draw_line_aa.o : egl/primitives/draw_line_aa.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}draw_polyfill.o : egl/primitives/draw_polyfill.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}bitmapfont.o : egl/font/bitmapfont.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_font.o : egl/font/egl_font.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}readfile.o : fatfs/readfile.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}egl_animation.o : egl/object/egl_animation.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}unicode_codec.o : egl/font/unicode_codec.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}fixed_sincos.o : egl/util/fixed_sincos.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}draw_legacy.o : egl/primitives/draw_legacy.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}draw_roundrect.o : egl/primitives/draw_roundrect.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}surface.o : egl/surface/surface.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}surface_createfrom.o : egl/surface/surface_createfrom.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}drawsurfacescale.o : egl/surface/drawsurfacescale.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}bitfont.o : egl/font/bitfont.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
${OBJDIR}textout_inbox.o : egl/font/textout_inbox.c
	@echo.exe 'Compile : $<'
	$(ECHOMARK)$(CC) $(CFLAGS) $(INCDIR) -c -fmessage-length=0 -MMD -MP -MF"$(@:.o=.d)" -MT"$(@:.o=.d)" -o "$@" "$<"
	@echo.exe ' '
